server:
  http_listen_port: 9080
  grpc_listen_port: 9095
  log_level: info

positions:
  filename: /etc/promtail/positions/positions.yaml

clients:
  - url: http://64.227.114.82:3100/loki/api/v1/push

scrape_configs:
- job_name: firehose-client
  pipeline_stages:
    - multiline:
        firstline: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}
        max_wait_time: 3s
    - regex:
        expression: "^\(?P<date_time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}.\\d{3}\\ \\[(?P<log_level>\\S+)\\] (?P<thread>\\S+) - (?P<log_entry>(?s:.*))$"
    - timestamp:
        source: date_time
    - label:
        loglevel:
    - output:
        source: log_entry
             
  static_configs:
  - targets:
      - localhost
    labels:
      job: firehose-client
      host: 64.227.114.82
      __path__: /firehose_client/logs/*.log