server:
  http_listen_port: 9080
  grpc_listen_port: 9095
  log_level: info

positions:
  filename: /etc/promtail/positions/positions.yaml

clients:
  - url: http://64.227.114.82:3100/loki/api/v1/push

scrape_configs:
  - job_name: firehose-client
    pipeline_stages:
      - multiline:
          firstline: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}
          max_wait_time: 3s
      - match:
          selector: '".* matched candidate .*"'
          stages:
            - regex:
                expression: "^(?P<date_time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}[.]\\d{3})\\s+(?P<log_level>\\S+)\\s+(?P<thread>\\S+) (?P<matched>.*) matched candidate (?P<target>(?s:.*))$"
            - timestamp:
                source: date_time
                format: "2006-01-02 15:16:17.018"
      - match:
          selector: '".* in message: .*"'
          stages:
            - regex:
                expression: "^(?P<date_time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}[.]\\d{3})\\s+(?P<log_level>\\S+)\\s+(?P<thread>\\S+) in message: (?P<message>.*)$"
            - timestamp:
                source: date_time
                format: "2006-01-02 15:16:17.018"
            - metrics:
                filter_match_lines:
                  type: Counter
                  description: "content matching any filter`"
                  source: message
                  config:
                    action: inc
      - metrics:
          log_lines_total:
            type: Counter
            description: "total number of log lines"
            config:
              match_all: true
              action: inc
          log_bytes_total:
            type: Counter
            description: "total bytes of log lines"
            config:
              match_all: true
              count_entry_bytes: true
              action: add

    static_configs:
      - targets:
          - localhost
        labels:
          job: firehose-client
          host: 165.227.146.55
          __path__: /var/logs/*.log
