# @NOTE: this compose file is intended to accompany the guide found in HOSTING.md

services:
  firehose-client:
    container_name: firehose-client
    image: ghcr.io/stevetownsend/firehose-client:latest
    network_mode: host
    volumes:
      - type: bind
        source: /firehose-client/logs/
        target: /firehose-client/logs/
      - type: bind
        source: /firehose-client/config/full_config_prod.yml
        target: /etc/firehose-client/full_config_prod.yml
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  promtail:
    image: grafana/promtail:latest
    network_mode: host
    volumes:
      - type: bind
        source: /firehose-client/logs/
        target: /var/logs/
      - /firehose-client/promtail/positions/:/etc/promtail/positions/
      - /firehose-client/config/promtail.yaml/:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  postgres:
    container_name: postgres
    image: postgres:17.2-bookworm
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - type: bind
        source: /firehose-client/postgres
        target: /var/lib/postgresql/data
    env_file:
      - /firehose-client/postgres.env
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  neo4j:
    image: neo4j:latest
    network_mode: host
    volumes:
        - /neo4j/logs:/logs
        - /neo4j/config:/config
        - /neo4j/data:/data
        - /neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    secrets:
      - neo4j_auth_file
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    network_mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_SCHEDULE: '@midnight'
      WATCHTOWER_LABEL_ENABLE: 'true'

secrets:
  neo4j_auth_file:
    file: /neo4j/secrets/neo4j_auth.txt
