# @NOTE: this compose file is intended to accompany the guide found in HOSTING.md
version: '3.9'
services:
  firehose-client:
    container_name: firehose-client
    image: ghcr.io/SteveTownsend0/ozone:0.1
    network_mode: host
    volumes:
      - type: bind
        source: /firehose-client/logs
        target: /usr/src/firehose-client/logs
    restart: unless-stopped
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    # env_file:
    #   - /ozone/ozone.env
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    network_mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: '@midnight'
      WATCHTOWER_LABEL_ENABLE: true