# @NOTE: this compose file is intended to accompany the guide found in HOSTING.md

services:
  firehose-client:
    container_name: firehose-client
    image: ghcr.io/stevetownsend/firehose-client:latest
    network_mode: host
    ports:
      - "59090:59090"
    volumes:
      - type: bind
        source: /firehose-client/logs/
        target: /firehose-client/logs/
      - type: bind
        source: /firehose-client/config/full_config_prod.yml
        target: /etc/firehose-client/full_config_prod.yml
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  promtail:
    image: grafana/promtail:latest
    network_mode: host
    volumes:
      - type: bind
        source: /firehose-client/logs/
        target: /var/logs/
      - /firehose-client/promtail/positions/:/etc/promtail/positions/
      - /firehose-client/config/promtail.yaml/:/etc/promtail/promtail.yaml
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    network_mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_SCHEDULE: '@midnight'
      WATCHTOWER_LABEL_ENABLE: 'true'

