firehose_client:
  logging:
    filename: "./logs/firehose_client_full.log"
    level: "info" # per spdlog values trace, debug, info, warn, error, critical, off

  filters:
    #filename: "./config/live_filters"
    use_db: true

  datasource:
    hosts:
      # full firehose
      "bsky.network"
    port: 443
    subscription: "/xrpc/com.atproto.sync.subscribeRepos"

  moderation_data:
    host: "104.248.47.218"
    port: 5432
    dbname: "ozone"
    user: "firehose_client"
    password: '1"XF5~NP,3*mk7@vD3i^'

  auxiliary_data:
    host: "165.227.146.55"
    port: 5432
    dbname: "moderation"
    user: "firehose_client"
    password: '};E"$$t*<Jl5Ys1|9TWC'

  auto_reporter:
    handle: "bonkamatic-9000.bsky.social"
    password: "EMj*-(qoG,IP0?#@7q4{"
    did: "did:plc:hyqqdsrb5o6i6kzniaqapazg"
    # this has to be the home PDS of the reporting account - using bsky.social sends reports to the platform
    # https://docs.bsky.app/docs/advanced-guides/api-directory#common-request-types
    host: "https://polypore.us-west.host.bsky.network/xrpc/"
    port: 443
    service_did: "did:plc:uac6er53o2pvr5y2qmvaf7hw"
    dry_run: true

  embed_checker:
    follow_links: true
    number_of_threads: 3

  list_manager:
    handle: "nafo-moderation.bsky.social"
    password: "2Eq#05dAt79\\wD=aPW*)"
    client_did: "did:plc:uac6er53o2pvr5y2qmvaf7hw"
    # this has to be the home PDS of the reporting account for authenticated requests
    # https://docs.bsky.app/docs/advanced-guides/api-directory#common-request-types
    host: "https://parasol.us-east.host.bsky.network/xrpc/"
    port: 443
    dry_run: true

  metrics:
    port: 59090
